spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:http://config-server:8888"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true
