spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8088
          predicates:
            - Path=/api/v1/orders/**
            - Path=/api/v1/checkout/**
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/v1/conversations/**
        - id: websocket-worker
          uri: ws://websocket-worker:8094
          predicates:
            - Path=/ws/**
        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/v1/shipping/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ecommerce-realm
          jwk-set-uri: http://keycloak:8080/realms/ecommerce-realm/protocol/openid-connect/certs


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true

# CORS Configuration
app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,http://localhost:4173}
