spring:
  application:
    name: review-service
  config:
    import: "optional:configserver:http://config-server:8888"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/review_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example.reviewservice: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
