spring.application.name=discovery-service
spring.config.import=optional:configserver:http://config-server:8888

server.port=8761

# Eureka Server - DO NOT register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Self-preservation off for dev
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000