spring:
  application:
    name: chat-service
  config:
    import: "optional:configserver:http://config-server:8888"
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://mongodb:27017/chat_db}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/chat_db}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    listener:
      ack-mode: manual
    consumer:
      group-id: chat-service-group
      persist-group-id: chat-persist-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "dto.WsMessage"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true

app:
  kafka:
    topic-in: ws.chat.inbound
    topic-out: ws.outbound